/**
 ******************************************************************************
 * @file           : lib.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Library body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

/* Includes ------------------------------------------------------------------*/


/** Functions ----------------------------------------------------------------*/
void myFunction(void)
{
    /* Loop forever */
	for(;;);
}
